package helper;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by tuyennguyen on 7/31/17.
 */
public class Generator {

    // Generate email
    // Return: an email generated by time stamp (string)
    public static String generateEmail() {
        String geEmail = "email" + generateNumber() + "@mailinator.com";
        return geEmail;
    }

    // Generate Password
    public static String generatePassword() {
        String gePassword = "pass" + generateNumber();
        return gePassword;
    }

    // Generate Username
    public static String generateUsername() {
        String geUsername = "user" + generateNumber();
        return geUsername;
    }

    // Generate Number
    public static String generateNumber() {
        String timeStamp = new SimpleDateFormat("yyMMddHHmmss").format(new Date());
        return timeStamp;
    }

    private static String currentTime() {
        return Long.toString(System.currentTimeMillis());
    }
}
